LogisticRegression_lbfgs:
  class: sklearn.linear_model.LogisticRegression
  params:
    solver: ["lbfgs"]
    penalty: ["l2"]  # null maps to Python None
    C: [0.01, 0.1, 1.0, 10.0]
    max_iter: [100, 200]

LogisticRegression_liblinear:
  class: sklearn.linear_model.LogisticRegression
  params:
    solver: ["liblinear"]
    penalty: ["l1", "l2"]
    C: [0.01, 0.1, 1.0, 10.0]
    max_iter: [100, 200]

RandomForestClassifier:
  class: sklearn.ensemble.RandomForestClassifier
  params:
    n_estimators: [50, 100, 200]
    max_depth: [3, 5, 10]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]

SVC:
  class: sklearn.svm.SVC
  params:
    C: [0.1, 1, 10]
    kernel: ["linear", "rbf"]
    gamma: ["scale", "auto"]
