columns:
  months_as_customer: int
  age: int
  policy_state: object
  policy_csl: object
  policy_deductable: int
  policy_annual_premium: float
  umbrella_limit: int
  insured_sex: object
  insured_education_level: object
  insured_occupation: object
  insured_hobbies: object
  insured_relationship: object
  capital-gains: int
  capital-loss: int
  incident_type: object
  collision_type: object
  incident_severity: object
  authorities_contacted: object
  incident_state: object
  incident_hour_of_the_day: int
  number_of_vehicles_involved: int
  property_damage: object
  bodily_injuries: int
  witnesses: int
  police_report_available: object
  total_claim_amount: int
  injury_claim: int
  property_claim: int
  vehicle_claim: int
  auto_make: object
  auto_year: int
  fraud_reported: object

target_column:
  - fraud_reported

drop_columns:
  - policy_number
  - policy_bind_date
  - incident_date
  - incident_location
  - auto_model
  - insured_zip
  - incident_city

numerical_columns:
  - months_as_customer
  - age
  - policy_deductable
  - policy_annual_premium
  - umbrella_limit
  - capital-gains
  - capital-loss
  - incident_hour_of_the_day
  - number_of_vehicles_involved
  - bodily_injuries
  - witnesses
  - total_claim_amount
  - injury_claim
  - property_claim
  - vehicle_claim
  - auto_year

categorical_columns:
  - policy_state
  - policy_csl
  - insured_sex
  - insured_education_level
  - insured_occupation
  - insured_hobbies
  - insured_relationship
  - incident_type
  - collision_type
  - incident_severity
  - authorities_contacted
  - incident_state
  - property_damage
  - police_report_available
  - auto_make
  - fraud_reported